# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  run-docker:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9']

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker
      run: |
        make docker-qa-build PYTHON_VERSION=${{matrix.python-version}}
    - name: Run Docker
      run: |
        .github/bump_version ./ minor > cloudbees/VERSION
        make docker-qa PYTHON_VERSION=${{matrix.python-version}}
    - name: Creating coverage report
      if: ${{ ( matrix.python-version == '3.8' ) }}
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.xml
        fail_ci_if_error: true
